/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanguijava;

import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class kapal extends javax.swing.JFrame {
    
    String cari;
    String sql;
    private void mencari_nama(){
        cari = txtCarinama.getText();
        int no = 1;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Kode Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Nama Kapten");
        model.addColumn("Asal");
        model.addColumn("Tujuan");
        model.addColumn("Keberangkatan");
        model.addColumn("Container");
        
            try{
                sql= "SELECT * FROM kapal WHERE nama_kapal LIKE '%"+cari+"%'";
                java.sql.Connection conn =(Connection)configconnectiontomysql.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                }tabelkapal.setModel(model);
                
            }catch(SQLException e){
                System.out.println("Error : "+e.getMessage());
            }
    }
    private void mencari_kode(){
        cari = txtCarikode.getText();
        int no = 1;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Kode Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Nama Kapten");
        model.addColumn("Asal");
        model.addColumn("Tujuan");
        model.addColumn("Keberangkatan");
        model.addColumn("Container");
        
            try{
                sql= "SELECT * FROM kapal WHERE kode_kapal LIKE '%"+cari+"%'";
                java.sql.Connection conn =(Connection)configconnectiontomysql.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                }tabelkapal.setModel(model);
                
            }catch(SQLException e){
                System.out.println("Error : "+e.getMessage());
            }
    }
    
    
    private void menampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Kode Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Nama Kapten");
        model.addColumn("Asal");
        model.addColumn("Tujuan");
        model.addColumn("Keberangkatan");
        model.addColumn("Container");
        
        try{
            int no = 1;
            sql = "SELECT * FROM kapal";
            java.sql.Connection conn =(Connection)configconnectiontomysql.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                    model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            tabelkapal.setModel(model);
        }catch(SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    public kapal() {
        initComponents();
        menampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkapal = new javax.swing.JTable();
        tbExit = new javax.swing.JButton();
        tbCarikode = new javax.swing.JButton();
        txtCarikode = new javax.swing.JTextField();
        kodekapal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCarinama = new javax.swing.JTextField();
        tbCariNama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Data Kapal");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Data Kapal");

        tabelkapal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelkapal);

        tbExit.setText("Exit");
        tbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExitActionPerformed(evt);
            }
        });

        tbCarikode.setText("Cari");
        tbCarikode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCarikodeActionPerformed(evt);
            }
        });

        txtCarikode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarikodeActionPerformed(evt);
            }
        });
        txtCarikode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarikodeKeyPressed(evt);
            }
        });

        kodekapal.setText("Kode Kapal :");

        jLabel2.setText("Nama Kapal :");

        txtCarinama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarinamaActionPerformed(evt);
            }
        });

        tbCariNama.setText("Cari");
        tbCariNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCariNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(467, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(370, 370, 370)
                        .addComponent(tbExit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCarinama))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kodekapal)
                                .addGap(18, 18, 18)
                                .addComponent(txtCarikode, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbCarikode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbCariNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbExit)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarikode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCarikode)
                    .addComponent(kodekapal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCarinama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCariNama))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_tbExitActionPerformed

    private void txtCarikodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarikodeActionPerformed
      
    }//GEN-LAST:event_txtCarikodeActionPerformed

    private void tbCarikodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCarikodeActionPerformed
        mencari_kode();
    }//GEN-LAST:event_tbCarikodeActionPerformed

    private void txtCarikodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarikodeKeyPressed
        
    }//GEN-LAST:event_txtCarikodeKeyPressed

    private void txtCarinamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarinamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarinamaActionPerformed

    private void tbCariNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCariNamaActionPerformed
        mencari_nama();
    }//GEN-LAST:event_tbCariNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kapal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kodekapal;
    private javax.swing.JTable tabelkapal;
    private javax.swing.JButton tbCariNama;
    private javax.swing.JButton tbCarikode;
    private javax.swing.JButton tbExit;
    private javax.swing.JTextField txtCarikode;
    private javax.swing.JTextField txtCarinama;
    // End of variables declaration//GEN-END:variables
}
